#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 31 22:05:24 2020

@author: caoyanan
"""

import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup 
import re
import csv
import codecs
import time


address = 'https://www.androidrank.org/android-most-popular-google-play-apps?category=ART_AND_DESIGN'

#outputpath=open("/Users/caoyanan/Desktop/canada/apps/catogery.csv",'a') 

#%% 整个网页
url = address
uh = urllib.request.urlopen(url)
print('Retrieving', url)
data = uh.read()

content = data.decode()
print(content)

soup = BeautifulSoup(content, "lxml")
#%% 排名网站

adds_cate = re.findall(r'<b><a href="/android-most-popular-google-play-apps(.*?)">', str(content))

cate1 = soup.select('b')
cate_name = []
for b in range(9,len(cate1)):
    cate_name.append(cate1[b].get_text())
print(cate_name)

n = len(adds_cate)
category_address = adds_cate[3:n]

print(category_address)

#%%
l = len(category_address)
for i in range(37,l): 
    app_rank_info_T = [["Rank","Title","Category","Total Rating","Installs","Average Rating","Growth(30 days)","Growth(60 days)","Price","URL"]]
    n2 = len(category_address[i])
    for j in range(1,500,20):
        rank_address = 'https://www.androidrank.org/android-most-popular-google-play-apps?start='+str(j)+'&sort=0&price=all&'+category_address[i][1:n2]       
        url = rank_address
        uh = urllib.request.urlopen(url)
        print('Retrieving', url)
        data = uh.read()
        content_rank = data.decode()
        soup = BeautifulSoup(content_rank, "lxml")
        info = soup.select('td')
        #print(info[0])
        adds_app = re.findall(r'<td style="text-align:left;"><a href="(.*?)">', str(content_rank))
        for a in range(0,len(info),9):
            app_rank_info = [info[a].get_text(), info[a+1].get_text(), cate_name[i], info[a+3].get_text(),
                             info[a+4].get_text(), info[a+5].get_text(), info[a+6].get_text(), info[a+7].get_text(),
                             info[a+8].get_text(), adds_app[int(a/9)]]
            app_rank_info_T.append(app_rank_info)
    print('运行至第'+str(i)+'类别')
    if i % 5 == 0:
        print('sleeping...')
        time.sleep(60)
        
    filename = '/Users/caoyanan/Desktop/canada/apps/data/'+cate_name[i]+'.csv'
    file_csv = codecs.open(filename, 'w', encoding='utf-8-sig')
    writer = csv.writer(file_csv)
    for d in app_rank_info_T:
        #print(d)
        writer.writerow(d)
    file_csv.close()

